<?php
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$this->headTitle( $title = $this->translate( 'applicationLog.list.title', 'applicationLog' ) );
$view   = $this;
$rowSet = $this->rowSet();

if ( ! $this->format ): ?>
<h1><?= $title ?></h1>
<?php endif ?>
<?= $this->rowSet( $this->paginator, $rowSet::FLAG_LAYOUT_ALL )
         ->setColumnTranslatePrefix( 'applicationLog.list.column' )
         ->setColumnTranslatePostfix( 'title' )
         ->setColumnTranslateTextDomain( 'applicationLog' )
         ->setItemCountPerPage( 25 )
         ->setPage( $this->page )
         ->setDefaultOrders( array(
             'timestamp'        => 'DESC',
         ) )
         ->setIcons( array(
             'priority'         => '/images/modules/ApplicationLog/priority/%s.png',
         ) )
         ->setNotSetLabels( array(
             'loggedUserName'   => 'applicationLog.anonymous',
         ) )
         ->setColumns( array(
             'priority'         => $rowSet->column( 'enum', array(
                                        '0' => '0',
                                        '1' => '1',
                                        '2' => '2',
                                        '3' => '3',
                                        '4' => '4',
                                        '5' => '5',
                                        '6' => '6',
                                        '7' => '7',
                                    ), 'applicationLog.priority', '', 'applicationLog' ),
             'eventType'        => $rowSet->column( 'enum', array(
                                        'user-login'    => 'user-login',
                                        'user-logout'   => 'user-logout',
                                        'content-view'  => 'content-view',
                                    ), 'applicationLog.eventType', '', 'applicationLog' ),
             'loggedUserName'   => $rowSet::STRING,
             'timestamp'        => $rowSet::DATETIME,
             'extra'            => function ( $row ) use ( $view ) {
                 return $row->render( $view );
             },
         ) )
         ->render( $this->format );

if ( ! $this->format ): ?>
<div class="more-links">
    <a class="button-appearance"
       data-js-type="js.ui.dialog.ajax" target="_blank"
       href="/app/<?= $view->locale() ?>/admin/application-log/export">
        <?= $view->translate( 'default.export' ); ?>
    </a>
</div>
<?php endif ?>
